# BACKGROUND: Monin  et al (2017), based on construal theory, predict that "that women who were high in marital satisfaction would experience the greatest distress on days when they perceived more than average levels of partner suffering. This is compared with men and women low in marital satisfaction and men high in marital satisfaction." 
# 
# STRATEGY: The DV is marital distress on a 1-4 scale ('not at all stressed' to 'very stressed'). Perceived physical suffering of pattern the IV was on a 1 ('did not suffer') to 10 ('suffered terribly') scale. So if distress increased with suffering in a simple way, and subjects used most of the scale points a fair amount of the time, one might expect 'no suffering' to go with 'no distress', i.e. the relationship to start with (1,1) and finish with 'terrible suffering' going with the most  distress, i..e the line would go through (10,4). To a first approximation, the slope would be expected to be (4-1)/(10-1) = 0.33 distress units per suffering units. But any variable that affected distress independently of suffering would reduce the relationship. So a  default is to treat the ratio of the scale ranges as a rough maximum. That is we would model the H1 for the relation of distress to suffering as a half-normal with an SD of 0.17.
# The presumption is that the authors, given theory and background knowledge, have chosen scales for which they expect reasonable coverage by data. This is an assumption about predictions from theory in context, not about whether the data actually provide reasonable coverage. That is it is an assumption about predictions of theory, not about the actual sample data testing theory. It is just a conjecture and may be wrong. But in the absence of past study to make predictions from, it does provide rough expectations.
# ANALYSIS: The authors believe that the relationship will hold well for partners with high marital satisfaction but not for those with low satisfaction.  They obtain a significant distress vs suffering slope for high satisfaction females, estimated from the graph as 0.22 distress rating units per suffering rating unit. (Remarkably, just considering the scale limits, plus assuming people will mostly use most of the scale, puts us in the right ball park.) As they don't give an exact p, we can't get an exact SE, but there is no doubt a Bayes factor would give good evidence. For the sake of argument take p < .001 as p = .001; this gives t(40) = 3.06 (df = 40 is a very rough guess based on the smallest df in their table - but the issue is what could be done in principle, and the answer will be roughly right). So SE = 0.22/3.06 = .07 distress units per suffering units.
# BH(0, 0.17) = 51.86, RR[0.027, 6.50]. Given the arguments for a plausible maximum of 0,33, and no grounds for thinking the effect below .05,  this amounts to a robust conclusion for evidence for the alternative.
# 
# Inference by intervals:
#   95% CI [.08, .36]. 
# Conclusion depends on minimally interesting effect size.  In terms of providing support for the null region, RR [0, .08], so a key question is whether an interesting effect size could be smaller than .08 distress units per suffering units.
# Now what we assess the evidence for one of the other cases. 
# For high satisfaction males,  b = .03, SE = .02, 95% [-.01, .05].
# BH(0,0.17) = 0.66, non-evidential. RR [0, 0.35]. The maximum scale factor is rather high given our arguments that a plausible maximum is around 0,33; so the conclusion is robust. Therefore the conclusion In the abstract that "men who were high in marital satisfaction  experienced heightened daily distress irrespective of their perceptions of level of spousal suffering," is not supported if "irrespective" is read as meaning 'no interaction with suffering'.
# Equivalence testing: depends on whether .05 distress units per suffering units exceeds a minimal interesting value.  If one were to agree that the finding is not evidential, RR[0, .05]; if evidential, RR [.05, ???].
# 
# CONCLUSION:
#   
#   Bayes factors and equivalence testing are easily added to any statistical technique that provides a parameter value tested by a z or t-test (i.e. use the normal approximation). The software we have been illustrating uses the normal approximation. (If one were worried about robustness issues, Wilcox, xxx, robust measure estimates and their robust standard errors could be used instead, with our software, so long as the normal approximation was still recommended for testing those estimates.)
# Now some points about using raw effect sizes for regression. Increasing noise in the DV - i.e. the distress scale - will flatten the standardized slope but leave the raw slope unchanged. On each day a single distress rating was taken. So the daily rating wold be pretty unreliable. Increasing its reliability will not affect the model of H1 we have been using; it will reduce the relevant SEs and so make the data more evidential, either way. Thus the preference for raw slopes. Any noise in the IV will affect both the raw and standardized slope. This is a nuisance for both methods. And in this study the IV was a one off rating. This helps motivate the use of "0.33" as a maximum, as a noisy IV makes smaller slopes more likely.
# 
